apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

# Tells Kustomize where your local charts live relative to this file
helmGlobals:
  chartHome: ../../../../charts

helmCharts:
- name: crud-frontend
  releaseName: frontend-prod
  valuesInline:
    image:
      repository: devopsflow999/crud-frontend
      tag: sha-initialprodtag
    replicaCount: 3
    strategyType: Canary
  version: 1.0.0
images:
- name: devopsflow999/crud-frontend
  newName: devopsflow999/crud-frontend
  newTag: v1.0.4
