apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Allocate 1 Gigabyte of storage from the host machine for data safety
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 # Databases should rarely be scaled past 1 using standard deployments to avoid split-brain data corruption
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "devopsadmin"
            - name: POSTGRES_PASSWORD
              value: "secretpassword"
            - name: POSTGRES_DB
              value: "app_production"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # Mount the volume to the exact data folder Postgres writes to
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # This name matches the exact DB_HOST string our backend looks for!
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Keep the database isolated inside the internal cluster network mesh