apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

# Tells Kustomize where your local charts live relative to this file
helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: crud-frontend
    releaseName: frontend-dev
    version: 1.0.0
    valuesInline:
      replicaCount: 1
      strategyType: RollingUpdate
      image:
        repository: devopsflow999/crud-frontend
        tag: sha-initialdevtag