apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vservice
spec:
  hosts:
    - "ironstore.local" # Linked to match your explicit domain route
  gateways:
    - {{ .Release.Name }}-gateway # Binds directly to the custom gateway above
  http:
    - name: primary
      route:
        - destination:
            host: {{ .Release.Name }}-stable
            port:
              number: 80
          weight: 100
        - destination:
            host: {{ .Release.Name }}-canary
            port:
              number: 80
          weight: 0