apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vservice
spec:
  hosts:
    - "ironstore.local"
  gateways:
    - istio-system/ironstore-shared-gateway # LINKED TO THE SHARED GATEWAY
  http:
    - name: backend-route # MUST match the route name in your backend Rollout spec
      match:
        - uri:
            prefix: /api/items
      rewrite:
        uri: /items
      route:
        - destination:
            host: {{ .Release.Name }}-stable
            port:
              number: 3000
          weight: 100
        - destination:
            host: {{ .Release.Name }}-canary
            port:
              number: 3000
          weight: 0