apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

# Tells Kustomize where your local charts live relative to this file
helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: crud-frontend
    releaseName: frontend-prod
    version: 1.0.0
    valuesInline:
      replicaCount: 3
      strategyType: Canary
      image:
        repository: devopsflow999/crud-frontend
        tag: sha-initialprodtag